### ISSUE TITLE
Force HTTPS over HTTP

### ISSUE THREAD

**Issue by schuermannator** [stev-ou/stev#25]

**Comment by samjett247** [comment]
@schuermannator This is done right? I checked on mine and I think it was enforcing https

**Comment by schuermannator** [comment]
no, still if you visit http://ou.evals.info it won't redirect. Still trying to investigate the best way to fix

**Comment by samjett247** [comment]
Can you add a CNAME entry to ou.evals.info to redirect to evals.info, which will redirect back to ou.evals.info but with enforced https? Lol its kinda a backwards route but might work 🤷‍♂

**Comment by schuermannator** [comment]
I'll investigate but can't say that sounds promising haha

**Comment by schuermannator** [comment]
### Hello Google Cloud Run Customer,

We are writing to let you know that in order to make Cloud Run secured by default, Cloud Run services will only be accessible via HTTPS.

**What do I need to know?**
Any HTTP requests to Cloud Run services will receive a 302 "Moved Temporarily" status code that redirects to the HTTPS location. Web browsers follow this redirection. Requests to Cloud Run services invoked via HTTP from clients which do not follow 302 redirects will start failing. To avoid any service disruption, please ensure your Cloud Run services are invoked using HTTPS (URLs that start with ‘https://’). This applies to both *.run.app endpoints and endpoints using custom domains.

**What do I need to do?**
If your Cloud Run service is invoked via HTTP from clients that do not follow redirects, please ensure the clients making the requests **use HTTPS by August 19, 2019**.

Your project(s) listed below have Cloud Run services that served over HTTP in the last 7 days:
- ou-reviews (ou-reviews)

If you have any questions or require assistance, please reply to this email to contact Google Cloud Support.

Thank you for being a valued Cloud Run customer.

**Comment by schuermannator** [comment]
Got this email that they are doing forceful migration to HTTPS. So we should be good. I'll close after validated

**Comment by schuermannator** [comment]
I'm getting automatically redirected on everything now @samjett247. Let me know if I'm missing anything, closing if not.

**Comment by samjett247** [comment]
Yup me too :) Thanks Google!
