### ISSUE TITLE
Different courses ~ Same course number

### ISSUE THREAD

**Issue by samjett247** [stev-ou/stev#37]
-ENGR1510
-ENGR4510

**Comment by samjett247** [comment]
Might not be a whole ton we can do about this, as its sort of a defect in the data, but just wanted to keep it logged.

**Comment by samjett247** [comment]
- Never fear, Sam Jett is here! Patched in backend; See [here](https://github.com/stev-ou/stev-api/pull/30) for PR, [here](https://github.com/stev-ou/stev-api/issues/29) for similar issue in backend.

**Comment by schuermannator** [comment]
@samjett247 Your efforts are noticed, appreciated, and excellent.
