### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by samjett247** [stev-ou/stev#5]

**Comment by samjett247** [comment]
DSA5970:  Fig1 API not working

**Comment by samjett247** [comment]
Sporadic CSS errors on Chrome

![image](https://user-images.githubusercontent.com/30481194/57200892-af464780-6f56-11e9-9825-e8456fc0e76d.png)

**Comment by samjett247** [comment]
engr4510

**Comment by schuermannator** [comment]
migrated
