### ISSUE TITLE
In the News page

### ISSUE THREAD

**Issue by samjett247** [stev-ou/stev#52]
If this OU daily article gets written, we should add a In the News page, or just append a section to our About

**Comment by schuermannator** [comment]
Agreed!

**Comment by samjett247** [comment]
We could also throw in a link to the OU Congress presentation and outcome

**Comment by schuermannator** [comment]
Yea I like that. I can try to hunt it down online or we can get back in touch with someone from SGA?

**Comment by samjett247** [comment]
Here's the link, we already have that included in the about page - > http://www.ou.edu/content/dam/sga/common/USG/Minutes/Session%20102/Congress%20Minutes%2004-23-19.pdf#page=5

**Comment by samjett247** [comment]
Addressed in #57
