### ISSUE TITLE
Missing Data for Instructor

### ISSUE THREAD

**Issue by AndrewReaganM** [stev-ou/stev#55]
The instructor "Le Gruenwald" (also "Gia-Loi Gruenwald") is missing from the catalog of instructors, or at least does not show up in a search.

When I looked into it further, it does not appear that the course shows up in the PDFs either.

**Comment by schuermannator** [comment]
Hey Andrew, thanks for opening an issue and doing some investigating! If the instructor isn’t in the PDF’s we likely have no way of ingesting it into our system. One thing worth noting is that instructors have the option to keep their reviews private, thereby removing any of their information from the PDF’s we scrape. 

I’ll try to do some looking as well and see if we can sort this out!

**Comment by AndrewReaganM** [comment]
Thanks for looking into it! It _might_ be a good idea to add that info somewhere on the site, as I had assumed that all evaluation data must be released and therefore it would all be public and searchable.

side note: great job on this project!

**Comment by samjett247** [comment]
Thans

> Thanks for looking into it! It _might_ be a good idea to add that info somewhere on the site, as I had assumed that all evaluation data must be released and therefore it would all be public and searchable.
> 
> side note: great job on this project!

Thanks for the feedback Andrew. I'm going to add a new issue for mentioning this in the _About_ or _Get Involved_ pages.
