### ISSUE TITLE
Inconsistent YAxes across instructors

### ISSUE THREAD

**Issue by samjett247** [stev-ou/stev#60]
Please make your rating axis go all the way to zero in the Y dimension.  Otherwise it could be said that you are trying to magnify differences in the data as the difference between 4.1, 4.2 and 3.5 looks like a massive drop.....

Dr. Thomas Hays

**Comment by schuermannator** [comment]
I'm seeing some courses (I guess with no reviews) where the mean is 0.

**Comment by samjett247** [comment]
That doesn't necessarily imply individual reviews are 0 - could be their alternative to a null value. I can look into individual values tonight, I think the best way is to check the pdfs from the source.

**Comment by schuermannator** [comment]
Yea I agree. But since we aggregated with 0's there are 0, 0.5 etc.

**Comment by samjett247** [comment]
Based on this, I think YAxes should go 1-5. Going to implement this
<img width="851" alt="Screen Shot 2019-12-02 at 9 40 14 AM" src="https://user-images.githubusercontent.com/30481194/69972729-be3ea980-14e7-11ea-8bc7-ea24fa596395.png">

**Comment by samjett247** [comment]
Okay, I played around with changing YAxes on range[1-5] and it just obscures any meaning you can get from the graph. Would be like if you plotted some parameter that varied from 80-90% on a 0-100% axis. It just doesnt convey meaning. I still made some changes in new branch; Will do PR in a second.

**Comment by samjett247** [comment]
Not making this change for now.
